<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://localhost:8000/api"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  name="MyService"
                  targetNamespace="http://localhost:8000/api">

    <wsdl:types>
        <xsd:schema targetNamespace="http://localhost:8000/api">
            <xsd:element name="IncrementNumberRequest">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="inputNumber" type="xsd:decimal"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="IncrementNumberResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="outputNumber" type="xsd:decimal"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="IncrementNumberRequestMessage">
        <wsdl:part name="parameters" element="tns:IncrementNumberRequest"/>
    </wsdl:message>

    <wsdl:message name="IncrementNumberResponseMessage">
        <wsdl:part name="parameters" element="tns:IncrementNumberResponse"/>
    </wsdl:message>

    <wsdl:portType name="MyServicePortType">
        <wsdl:operation name="IncrementNumber">
            <wsdl:input message="tns:IncrementNumberRequestMessage"/>
            <wsdl:output message="tns:IncrementNumberResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="MyServiceBinding" type="tns:MyServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="IncrementNumber">
            <soap:operation soapAction="http://localhost:8000/api/IncrementNumber"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="MyService">
        <wsdl:port name="MyServicePort" binding="tns:MyServiceBinding">
            <soap:address location="http://localhost:8000/api"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
